Fix a few errors (#55)
* Fix error masking

Message "TypeError: err.replace is not a function" because caught error is not a string

* Build command correctly

* Update SDK dependency